INSERT INTO configurations (name,value,description,deleted_at,created_at,updated_at) VALUES
    ('wwwroot','http://www.treinaend.com.br','URL do site',NULL,NOW(),NULL),
    ('dataroot','/var/www/html/treinaend.com.br/web/','Caminho físico',NULL,NOW(),NULL),
    ('destinatariocontato','comercial@treinaend.com.br','E-mail do destinatário do formulário de contato',NULL,NOW(),NULL),
    ('destinatarionomecontato','Treinaend','Nome do destinatário do formulário de contato',NULL,NOW(),NULL),
    ('remetentecontato','comercial@treinaend.com.br','E-mail do remetente do formulário de contato',NULL,NOW(),NULL),
    ('remetentenomecontato','Treinaend','Nome do remetente do formulário de contato',NULL,NOW(),NULL),
    ('destinatariosugestoes','sugestoes_ead@treinaend.com.br','E-mail do destinatário do formulário de sugestões',NULL,NOW(),NULL),
    ('nomesugestoes','Treinaend','Nome do destinatário do formulário de sugestões',NULL,NOW(),NULL),
    ('destinatarioarquivos','arquivos_ead@treinaend.com.br','E-mail do destinatário do formulário de arquivos',NULL,NOW(),NULL),
    ('nomearquivos','Treinaend','Nome do destinatário do formulário de arquivos',NULL,NOW(),NULL),
    ('remetenteemail','login_ead@treinaend.com.br','E-mail do remetente da função incluir aluno',NULL,NOW(),NULL),
    ('remetentenomeemail','Treinaend','Nome do remetente da função incluir aluno',NULL,NOW(),NULL),
    ('remetenterecuperacaosenha','login_ead@treinaend.com.br','E-mail do remetente da função de recuperação de senha',NULL,NOW(),NULL),
    ('nomerecuperacaosenha','Treinaend','Nome do remetente da função de recuperação de senha',NULL,NOW(),NULL),
    ('admin','admin','Nome de usuário do administrador',NULL,NOW(),NULL),
    ('usuariosmtp','login_ead@treinaend.com.br','Configurações para autenticação do envio smtp',NULL,NOW(),NULL),
    ('senhasmtp','nala1976','Configurações para autenticação do envio smtp',NULL,NOW(),NULL),
    ('hostsmtp','smtp.treinaend.com.br','Configurações para autenticação do envio smtp',NULL,NOW(),NULL),
    ('portasmtp','587','Configurações para autenticação do envio smtp',NULL,NOW(),NULL),
    ('urlredir','http://treinaend.dominiotemporario.com','PagSeguro: URL de redirecionamento',NULL,NOW(),NULL),
    ('urlredir','http://treinaend.dominiotemporario.com/pagseguro/retorno.php','PagSeguro: URL de retorno automático',NULL,NOW(),NULL),
    ('emailpagseguro','pagseguro@treinaend.com.br','PagSeguro: E-mail',NULL,NOW(),NULL),
    ('tokenpagseguro','DDDB4D717A91496AB985A0542CB6835C','PagSeguro: Token',NULL,NOW(),NULL),
    ('Tabela_Estado_Padrao','0','Valor padrão, da tabela ead_cur_uf, quando o Estado não é localizado.',NULL,NOW(),NULL),
    ('Valor_Curso_Padrao','00,00','Valor padrão dos cursos em caso do sistema não localizar o ID do Curso.',NULL,NOW(),NULL),
    ('valortentativaminima','3','Usado na sql do sistema de exercicios e prova',NULL,NOW(),NULL),
    ('destinarioconclusao','alan@treinaend.com.br','E-mail que receberá alerta de conclusão do curso',NULL,NOW(),NULL);
