INSERT INTO disciplines (name,`order`,days,deleted_at,created_at,updated_at) VALUES
    ('Noções de Processamentos Químicos e Outros',1,1,NULL,NOW(),NULL),
    ('Segurança e Saúde no Trabalho',2,1,NULL,NOW(),NULL),
    ('Noções sobre Qualidade',3,1,NULL,NOW(),NULL),
    ('Noções sobre Proteção Ambiental',4,1,NULL,NOW(),NULL),
    ('Noções sobre Aspéctos Legais da Insp. Equip.',5,1,NULL,NOW(),NULL),
    ('Papel da Inspeção de Equipamentos nas Organizações',6,1,NULL,NOW(),NULL),
    ('Normalização Técnica',7,1,NULL,NOW(),NULL),
    ('Metrologia',8,1,NULL,NOW(),NULL),
    ('Desenho Técnico',9,1,NULL,NOW(),NULL),
    ('Relatórios de Inspeção',10,1,NULL,NOW(),NULL),
    ('Metalurgia e Materiais Metálicos',11,1,NULL,NOW(),NULL),
    ('Soldagem',12,1,NULL,NOW(),NULL),
    ('Corrosão e Monitoração da Corrosão',13,1,NULL,NOW(),NULL),
    ('Causas de Deterioração de Equipamentos',14,1,NULL,NOW(),NULL),
    ('Materiais Não Metálicos',15,1,NULL,NOW(),NULL),
    ('Refratários e Isolantes',16,1,NULL,NOW(),NULL),
    ('Pintura e Revestimentos Não Metálicos',17,1,NULL,NOW(),NULL),
    ('Revestimentos Metálicos',18,1,NULL,NOW(),NULL),
    ('Proteção Catódica',19,1,NULL,NOW(),NULL),
    ('Tratamento de Água e Inibidores de Corrosão',20,1,NULL,NOW(),NULL),
    ('Iluminação e Inspeção Visual',21,1,NULL,NOW(),NULL),
    ('Líquido Penetrante',22,1,NULL,NOW(),NULL),
    ('Partículas Magnéticas',23,1,NULL,NOW(),NULL),
    ('Radiografia - Inperpretação radiográfica',24,1,NULL,NOW(),NULL),
    ('Medição de Espessura',25,1,NULL,NOW(),NULL),
    ('Ultrassom',26,1,NULL,NOW(),NULL),
    ('Noções de ENDs não Convencionais',27,1,NULL,NOW(),NULL),
    ('Fotografia',28,1,NULL,NOW(),NULL),
    ('Metalografia',29,1,NULL,NOW(),NULL),
    ('Ensaios Mecânicos',30,1,NULL,NOW(),NULL),
    ('Termografia',31,1,NULL,NOW(),NULL),
    ('Avaliação de Taxas de Corrosão',32,1,NULL,NOW(),NULL),
    ('Avaliação de Vida Residual',33,1,NULL,NOW(),NULL),
    ('Identificação de Metais',34,1,NULL,NOW(),NULL),
    ('Vasos de Pressão e Torres',35,1,NULL,NOW(),NULL),
    ('Permutadores de Calor',36,1,NULL,NOW(),NULL),
    ('Tanques de Armazenamento',37,1,NULL,NOW(),NULL),
    ('Tubulações e Dutos',38,1,NULL,NOW(),NULL),
    ('Caldeiras',39,1,NULL,NOW(),NULL),
    ('Fornos',40,1,NULL,NOW(),NULL),
    ('Válvulas de Segurança',41,1,NULL,NOW(),NULL),
    ('Torres de Refrigeração',42,1,NULL,NOW(),NULL),
    ('Inspeção de Fabricação',43,1,NULL,NOW(),NULL);
